//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServiceJava
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", ConfigurationName="SOAPServiceJava.MensajeServiceSoap", CallbackContract=typeof(SOAPServiceJava.MensajeServiceSoapCallback))]
    public interface MensajeServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SOAPServiceJava.postMensajeResponse1> postMensajeAsync(SOAPServiceJava.postMensajeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SOAPServiceJava.postMensajeRespuestaResponse1> postMensajeRespuestaAsync(SOAPServiceJava.postMensajeRespuestaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task getTraerMensajePorAutorAsync(SOAPServiceJava.getTraerMensajePorAutorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task getTraerMensajePorReceptorAsync(SOAPServiceJava.getTraerMensajePorReceptorRequest1 request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MensajeServiceSoapCallback
    {
        
        // CODEGEN: Generating message contract since the operation getTraerMensaje is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getTraerMensaje(SOAPServiceJava.getTraerMensajeResponse request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class postMensajeRequest
    {
        
        private long idAutorField;
        
        private long idReceptorField;
        
        private string asuntoField;
        
        private string mensajeField;
        
        private string respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idAutor
        {
            get
            {
                return this.idAutorField;
            }
            set
            {
                this.idAutorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long idReceptor
        {
            get
            {
                return this.idReceptorField;
            }
            set
            {
                this.idReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string asunto
        {
            get
            {
                return this.asuntoField;
            }
            set
            {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class mensaje
    {
        
        private long idMensajeField;
        
        private string nombreAutorField;
        
        private string nombreReceptorField;
        
        private string asuntoField;
        
        private string mensaje1Field;
        
        private string respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idMensaje
        {
            get
            {
                return this.idMensajeField;
            }
            set
            {
                this.idMensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreAutor
        {
            get
            {
                return this.nombreAutorField;
            }
            set
            {
                this.nombreAutorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreReceptor
        {
            get
            {
                return this.nombreReceptorField;
            }
            set
            {
                this.nombreReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string asunto
        {
            get
            {
                return this.asuntoField;
            }
            set
            {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Order=4)]
        public string mensaje1
        {
            get
            {
                return this.mensaje1Field;
            }
            set
            {
                this.mensaje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class postMensajeResponse
    {
        
        private mensaje mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public mensaje mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postMensajeRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        public SOAPServiceJava.postMensajeRequest postMensajeRequest;
        
        public postMensajeRequest1()
        {
        }
        
        public postMensajeRequest1(SOAPServiceJava.postMensajeRequest postMensajeRequest)
        {
            this.postMensajeRequest = postMensajeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postMensajeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        public SOAPServiceJava.postMensajeResponse postMensajeResponse;
        
        public postMensajeResponse1()
        {
        }
        
        public postMensajeResponse1(SOAPServiceJava.postMensajeResponse postMensajeResponse)
        {
            this.postMensajeResponse = postMensajeResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTraerMensajeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTraerMensajeResponse", Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensajes", IsNullable=false)]
        public SOAPServiceJava.mensaje[] getTraerMensajeResponse1;
        
        public getTraerMensajeResponse()
        {
        }
        
        public getTraerMensajeResponse(SOAPServiceJava.mensaje[] getTraerMensajeResponse1)
        {
            this.getTraerMensajeResponse1 = getTraerMensajeResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class postMensajeRespuestaRequest
    {
        
        private long mensajeIdField;
        
        private string respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mensajeId
        {
            get
            {
                return this.mensajeIdField;
            }
            set
            {
                this.mensajeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class postMensajeRespuestaResponse
    {
        
        private mensaje mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public mensaje mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postMensajeRespuestaRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        public SOAPServiceJava.postMensajeRespuestaRequest postMensajeRespuestaRequest;
        
        public postMensajeRespuestaRequest1()
        {
        }
        
        public postMensajeRespuestaRequest1(SOAPServiceJava.postMensajeRespuestaRequest postMensajeRespuestaRequest)
        {
            this.postMensajeRespuestaRequest = postMensajeRespuestaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postMensajeRespuestaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        public SOAPServiceJava.postMensajeRespuestaResponse postMensajeRespuestaResponse;
        
        public postMensajeRespuestaResponse1()
        {
        }
        
        public postMensajeRespuestaResponse1(SOAPServiceJava.postMensajeRespuestaResponse postMensajeRespuestaResponse)
        {
            this.postMensajeRespuestaResponse = postMensajeRespuestaResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class getTraerMensajePorAutorRequest
    {
        
        private long idAutorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idAutor
        {
            get
            {
                return this.idAutorField;
            }
            set
            {
                this.idAutorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTraerMensajePorAutorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        public SOAPServiceJava.getTraerMensajePorAutorRequest getTraerMensajePorAutorRequest;
        
        public getTraerMensajePorAutorRequest1()
        {
        }
        
        public getTraerMensajePorAutorRequest1(SOAPServiceJava.getTraerMensajePorAutorRequest getTraerMensajePorAutorRequest)
        {
            this.getTraerMensajePorAutorRequest = getTraerMensajePorAutorRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.chefEncasa.com/demosoap/gen")]
    public partial class getTraerMensajePorReceptorRequest
    {
        
        private long idReceptorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idReceptor
        {
            get
            {
                return this.idReceptorField;
            }
            set
            {
                this.idReceptorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTraerMensajePorReceptorRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.chefEncasa.com/demosoap/gen", Order=0)]
        public SOAPServiceJava.getTraerMensajePorReceptorRequest getTraerMensajePorReceptorRequest;
        
        public getTraerMensajePorReceptorRequest1()
        {
        }
        
        public getTraerMensajePorReceptorRequest1(SOAPServiceJava.getTraerMensajePorReceptorRequest getTraerMensajePorReceptorRequest)
        {
            this.getTraerMensajePorReceptorRequest = getTraerMensajePorReceptorRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MensajeServiceSoapChannel : SOAPServiceJava.MensajeServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MensajeServiceSoapClientBase : System.ServiceModel.DuplexClientBase<SOAPServiceJava.MensajeServiceSoap>, SOAPServiceJava.MensajeServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MensajeServiceSoapClientBase(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance, MensajeServiceSoapClientBase.GetDefaultBinding(), MensajeServiceSoapClientBase.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MensajeServiceSoapSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajeServiceSoapClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration) : 
                base(callbackInstance, MensajeServiceSoapClientBase.GetBindingForEndpoint(endpointConfiguration), MensajeServiceSoapClientBase.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajeServiceSoapClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(callbackInstance, MensajeServiceSoapClientBase.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajeServiceSoapClientBase(System.ServiceModel.InstanceContext callbackInstance, EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, MensajeServiceSoapClientBase.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajeServiceSoapClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceJava.postMensajeResponse1> SOAPServiceJava.MensajeServiceSoap.postMensajeAsync(SOAPServiceJava.postMensajeRequest1 request)
        {
            return base.Channel.postMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceJava.postMensajeResponse1> postMensajeAsync(SOAPServiceJava.postMensajeRequest postMensajeRequest)
        {
            SOAPServiceJava.postMensajeRequest1 inValue = new SOAPServiceJava.postMensajeRequest1();
            inValue.postMensajeRequest = postMensajeRequest;
            return ((SOAPServiceJava.MensajeServiceSoap)(this)).postMensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceJava.postMensajeRespuestaResponse1> SOAPServiceJava.MensajeServiceSoap.postMensajeRespuestaAsync(SOAPServiceJava.postMensajeRespuestaRequest1 request)
        {
            return base.Channel.postMensajeRespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceJava.postMensajeRespuestaResponse1> postMensajeRespuestaAsync(SOAPServiceJava.postMensajeRespuestaRequest postMensajeRespuestaRequest)
        {
            SOAPServiceJava.postMensajeRespuestaRequest1 inValue = new SOAPServiceJava.postMensajeRespuestaRequest1();
            inValue.postMensajeRespuestaRequest = postMensajeRespuestaRequest;
            return ((SOAPServiceJava.MensajeServiceSoap)(this)).postMensajeRespuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SOAPServiceJava.MensajeServiceSoap.getTraerMensajePorAutorAsync(SOAPServiceJava.getTraerMensajePorAutorRequest1 request)
        {
            return base.Channel.getTraerMensajePorAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task getTraerMensajePorAutorAsync(SOAPServiceJava.getTraerMensajePorAutorRequest getTraerMensajePorAutorRequest)
        {
            SOAPServiceJava.getTraerMensajePorAutorRequest1 inValue = new SOAPServiceJava.getTraerMensajePorAutorRequest1();
            inValue.getTraerMensajePorAutorRequest = getTraerMensajePorAutorRequest;
            return ((SOAPServiceJava.MensajeServiceSoap)(this)).getTraerMensajePorAutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SOAPServiceJava.MensajeServiceSoap.getTraerMensajePorReceptorAsync(SOAPServiceJava.getTraerMensajePorReceptorRequest1 request)
        {
            return base.Channel.getTraerMensajePorReceptorAsync(request);
        }
        
        public System.Threading.Tasks.Task getTraerMensajePorReceptorAsync(SOAPServiceJava.getTraerMensajePorReceptorRequest getTraerMensajePorReceptorRequest)
        {
            SOAPServiceJava.getTraerMensajePorReceptorRequest1 inValue = new SOAPServiceJava.getTraerMensajePorReceptorRequest1();
            inValue.getTraerMensajePorReceptorRequest = getTraerMensajePorReceptorRequest;
            return ((SOAPServiceJava.MensajeServiceSoap)(this)).getTraerMensajePorReceptorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MensajeServiceSoapSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MensajeServiceSoapSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MensajeServiceSoapClientBase.GetBindingForEndpoint(EndpointConfiguration.MensajeServiceSoapSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MensajeServiceSoapClientBase.GetEndpointAddress(EndpointConfiguration.MensajeServiceSoapSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            MensajeServiceSoapSoap11,
        }
    }
    
    public class getTraerMensajeReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public getTraerMensajeReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public SOAPServiceJava.getTraerMensajeResponse request
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((SOAPServiceJava.getTraerMensajeResponse)(this.results[0]));
            }
        }
    }
    
    public partial class MensajeServiceSoapClient : MensajeServiceSoapClientBase
    {
        
        public MensajeServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                this(new MensajeServiceSoapClientCallback(), endpointConfiguration)
        {
        }
        
        private MensajeServiceSoapClient(MensajeServiceSoapClientCallback callbackImpl, EndpointConfiguration endpointConfiguration) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), endpointConfiguration)
        {
            callbackImpl.Initialize(this);
        }
        
        public MensajeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new MensajeServiceSoapClientCallback(), binding, remoteAddress)
        {
        }
        
        private MensajeServiceSoapClient(MensajeServiceSoapClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public MensajeServiceSoapClient() : 
                this(new MensajeServiceSoapClientCallback())
        {
        }
        
        private MensajeServiceSoapClient(MensajeServiceSoapClientCallback callbackImpl) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl))
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<getTraerMensajeReceivedEventArgs> getTraerMensajeReceived;
        
        private void OngetTraerMensajeReceived(object state)
        {
            if ((this.getTraerMensajeReceived != null))
            {
                object[] results = ((object[])(state));
                this.getTraerMensajeReceived(this, new getTraerMensajeReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class MensajeServiceSoapClientCallback : object, MensajeServiceSoapCallback
        {
            
            private MensajeServiceSoapClient proxy;
            
            public void Initialize(MensajeServiceSoapClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void getTraerMensaje(SOAPServiceJava.getTraerMensajeResponse request)
            {
                this.proxy.OngetTraerMensajeReceived(new object[] {
                            request});
            }
        }
    }
}
