//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recetario", Namespace="http://schemas.datacontract.org/2004/07/SOAPService")]
    public partial class Recetario : object
    {
        
        private int idRecetarioField;
        
        private string nombreField;
        
        private SOAPServiceReference.Receta[] recetasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRecetario
        {
            get
            {
                return this.idRecetarioField;
            }
            set
            {
                this.idRecetarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServiceReference.Receta[] recetas
        {
            get
            {
                return this.recetasField;
            }
            set
            {
                this.recetasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receta", Namespace="http://schemas.datacontract.org/2004/07/SOAPService")]
    public partial class Receta : object
    {
        
        private string[] ComentariosField;
        
        private SOAPServiceReference.FotoObj[] FotosField;
        
        private int IdRecetaField;
        
        private SOAPServiceReference.IngredienteObj[] IngredientesField;
        
        private SOAPServiceReference.PasoObj[] PasosField;
        
        private string categoriaField;
        
        private string descripcionField;
        
        private decimal promedioField;
        
        private int tiempoAproxField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Comentarios
        {
            get
            {
                return this.ComentariosField;
            }
            set
            {
                this.ComentariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServiceReference.FotoObj[] Fotos
        {
            get
            {
                return this.FotosField;
            }
            set
            {
                this.FotosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReceta
        {
            get
            {
                return this.IdRecetaField;
            }
            set
            {
                this.IdRecetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServiceReference.IngredienteObj[] Ingredientes
        {
            get
            {
                return this.IngredientesField;
            }
            set
            {
                this.IngredientesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServiceReference.PasoObj[] Pasos
        {
            get
            {
                return this.PasosField;
            }
            set
            {
                this.PasosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal promedio
        {
            get
            {
                return this.promedioField;
            }
            set
            {
                this.promedioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tiempoAprox
        {
            get
            {
                return this.tiempoAproxField;
            }
            set
            {
                this.tiempoAproxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FotoObj", Namespace="http://schemas.datacontract.org/2004/07/SOAPService")]
    public partial class FotoObj : object
    {
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IngredienteObj", Namespace="http://schemas.datacontract.org/2004/07/SOAPService")]
    public partial class IngredienteObj : object
    {
        
        private string CantidadField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasoObj", Namespace="http://schemas.datacontract.org/2004/07/SOAPService")]
    public partial class PasoObj : object
    {
        
        private string DescripcionField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SOAPService")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPServiceReference.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearMensaje", ReplyAction="http://tempuri.org/IService1/CrearMensajeResponse")]
        System.Threading.Tasks.Task<string> CrearMensajeAsync(int idAutor, int idReceptor, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ResponderMensaje", ReplyAction="http://tempuri.org/IService1/ResponderMensajeResponse")]
        System.Threading.Tasks.Task<string> ResponderMensajeAsync(int idMensaje, string respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerMensajesPorAutor", ReplyAction="http://tempuri.org/IService1/TraerMensajesPorAutorResponse")]
        System.Threading.Tasks.Task<string> TraerMensajesPorAutorAsync(int idAutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerMensajesPorReceptor", ReplyAction="http://tempuri.org/IService1/TraerMensajesPorReceptorResponse")]
        System.Threading.Tasks.Task<string> TraerMensajesPorReceptorAsync(int idReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearRecetario", ReplyAction="http://tempuri.org/IService1/CrearRecetarioResponse")]
        System.Threading.Tasks.Task<bool> CrearRecetarioAsync(int idAutor, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrarRecetario", ReplyAction="http://tempuri.org/IService1/BorrarRecetarioResponse")]
        System.Threading.Tasks.Task<bool> BorrarRecetarioAsync(int idRecetario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRecetariosPorUsuario", ReplyAction="http://tempuri.org/IService1/TraerRecetariosPorUsuarioResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Recetario[]> TraerRecetariosPorUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerRecetarioConRecetas", ReplyAction="http://tempuri.org/IService1/TraerRecetarioConRecetasResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Recetario> TraerRecetarioConRecetasAsync(int idRecetario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarRecetaRecetario", ReplyAction="http://tempuri.org/IService1/AgregarRecetaRecetarioResponse")]
        System.Threading.Tasks.Task<bool> AgregarRecetaRecetarioAsync(int idRecetario, int idReceta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoverRecetaRecetario", ReplyAction="http://tempuri.org/IService1/RemoverRecetaRecetarioResponse")]
        System.Threading.Tasks.Task<bool> RemoverRecetaRecetarioAsync(int idRecetario, int idReceta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.CompositeType> GetDataUsingDataContractAsync(SOAPServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : SOAPServiceReference.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SOAPServiceReference.IService1>, SOAPServiceReference.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<string> CrearMensajeAsync(int idAutor, int idReceptor, string asunto, string mensaje)
        {
            return base.Channel.CrearMensajeAsync(idAutor, idReceptor, asunto, mensaje);
        }
        
        public System.Threading.Tasks.Task<string> ResponderMensajeAsync(int idMensaje, string respuesta)
        {
            return base.Channel.ResponderMensajeAsync(idMensaje, respuesta);
        }
        
        public System.Threading.Tasks.Task<string> TraerMensajesPorAutorAsync(int idAutor)
        {
            return base.Channel.TraerMensajesPorAutorAsync(idAutor);
        }
        
        public System.Threading.Tasks.Task<string> TraerMensajesPorReceptorAsync(int idReceptor)
        {
            return base.Channel.TraerMensajesPorReceptorAsync(idReceptor);
        }
        
        public System.Threading.Tasks.Task<bool> CrearRecetarioAsync(int idAutor, string nombre)
        {
            return base.Channel.CrearRecetarioAsync(idAutor, nombre);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarRecetarioAsync(int idRecetario)
        {
            return base.Channel.BorrarRecetarioAsync(idRecetario);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Recetario[]> TraerRecetariosPorUsuarioAsync(int idUsuario)
        {
            return base.Channel.TraerRecetariosPorUsuarioAsync(idUsuario);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Recetario> TraerRecetarioConRecetasAsync(int idRecetario)
        {
            return base.Channel.TraerRecetarioConRecetasAsync(idRecetario);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarRecetaRecetarioAsync(int idRecetario, int idReceta)
        {
            return base.Channel.AgregarRecetaRecetarioAsync(idRecetario, idReceta);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverRecetaRecetarioAsync(int idRecetario, int idReceta)
        {
            return base.Channel.RemoverRecetaRecetarioAsync(idRecetario, idReceta);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.CompositeType> GetDataUsingDataContractAsync(SOAPServiceReference.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50101/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
