export const USUARIOS = [
  {
    id: 1,
    nombre: "Francisco",
    email: "francisco-armendariz@gmail.com",
    usuario: "fran21",
  },
  {
    id: 2,
    nombre: "Nicolas",
    email: "Nicolas-mail@Hotmail.com",
    usuario: "Nico123",
  },
  {
    id: 3,
    nombre: "Valentin",
    email: "Valentin-Topssian@gmail.com",
    usuario: "Valen7",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
  {
    id: 4,
    nombre: "Franco",
    email: "franco.Ponce@outlook.com",
    usuario: "fran00",
  },
];
